buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:8.5.2"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.24"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

subprojects {
    // Apply a safe default for unit tests to prevent CI failures when no tests are discovered
    tasks.withType(Test).configureEach {
        // Do not fail task when no tests are discovered
        ignoreFailures = false
        systemProperty "junit.platform.output.capture.stdout", "true"
        systemProperty "junit.platform.output.capture.stderr", "true"
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
