dependencies {
    testImplementation "junit:junit:4.13.2"
}

android {
    testOptions {
        unitTests.all {
            useJUnit() // ensure JUnit4 runner
            it.setFailOnNoMatchingTests(false)
            if (it.hasProperty("failOnNoDiscoveredTests")) {
                it.failOnNoDiscoveredTests = false
            }
        }
    }
}

tasks.withType(Test).configureEach { t ->
    t.include "**/*Test.class", "**/*Tests.class", "**/*TestSuite.class"
    t.setFailOnNoMatchingTests(false)
    if (t.hasProperty("failOnNoDiscoveredTests")) {
        t.failOnNoDiscoveredTests = false
    }
}
